spring.application.name=OnlineDrive
server.port=8080

spring.data.mongodb.uri=mongodb://host.docker.internal:27017/staasdb
spring.data.mongodb.database=staasdb

# AWS S3 Configuration
# Credentials are
# loaded automatically from environment variables
aws.s3.region=ca-central-1
aws.s3.bucket=${S3_BUCKET}
aws.s3.presigned.duration.minutes=15
